[package]
name = "imxrt-enet"
version = "0.1.0"
edition = "2021"

[dependencies]
ral-registers = "0.1"
imxrt-ral = "0.5"
mdio = "0.1"
defmt = "0.3"

[dependencies.smoltcp]
version = "0.12"
default-features = false
features = [
    "medium-ethernet",
    "proto-ipv4",
]
